### ISSUE TITLE
Plans on releasing a TypeScript type?

### ISSUE THREAD

**Issue by tomcanac** [riyadhalnur/mongoose-softdelete#6]
Hi, everything is in the question:

Are there any plans on doing a TypeScript definition? Would be amazing to have the autocompletion features and validation.

Thanks for any information :)
Tom

**Comment by riyadhalnur** [comment]
Definitely something worth introducing. Thanks for the suggestion.

**Comment by riyadhalnur** [comment]
I released a new version of this plugin v1.1.0 that adds types. Please try it out and let me know if it works for your use case. Cheers!

**Comment by tomcanac** [comment]
Hi,

I do have some problems here, I put them here, let me know if you think this is the type definition or my implementation.

1- I used `import mongooseSoftDelete from "mongoose-softdelete";` instead of require, because with Require, TS seems to cast the plugin to a type of any (thus, deactivating TS type). So here is my first not-by-the-doc line.

2- I tried to import the plugin in my root mongoose file and apply this to the mongoose global object, like this:
```
  mongoose.connect(uri, connectionParams);
  mongoose.plugin(mongooseSoftDelete);
```

and It gives me this warning:

```
Argument of type 'typeof import("/home/user/work/project-api/node_modules/mongoose-softdelete/index")' is not assignable to parameter of type '(schema: Schema<any>) => void'.
  Type 'typeof import("/home/user/work/projet-api/node_modules/mongoose-softdelete/index")' provides no match for the signature '(schema: Schema<any>): void'.ts(2345)
```

Note that even when I add the plugin directly to my schemas, It gives me the same warning.

Do you experience the same errors or does it looks like it is on my side?
Thanks for the help!

**Comment by madeindjs** [comment]
I resolved typing issue with this

~~~ts
import softDelete from 'mongoose-softdelete';
// ...
userSchema.plugin(softDelete as () => Schema<any>);
~~~

Also maybe it is simplier to make a PR on https://github.com/DefinitelyTyped/DefinitelyTyped ?

**Comment by riyadhalnur** [comment]
@madeindjs PRs are always welcomed 😃

**Comment by madeindjs** [comment]
@riyadhalnur , I made a simple PR :wink:
